# database driver jar names
mysql_driver_jar_name : "mysql-connector-java-8.0.15.jar"
mssql_driver_jar_name : ""
clickhouse_driver_jar_name : ""
postgres_driver_jar_name : ""

# processor-group-id for client
Processor_Group_Id : "e4594710-0171-1000-beca-5ca2813e28fb"
Global_Processor_Group_Id : "28065892-016c-1000-5653-27df94e6088b"
serverURL : "http://101.53.156.70:8181"